import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Download, Trash2, Circle, RefreshCw, Lock } from "lucide-react";
import { useUi, type Theme } from "@/store/ui";
import {
  useModels,
  useOllamaStatus,
  useModelMutations,
  useDownloadProgress,
} from "@/hooks/useModels";
import { type ModelInfo, diarizeApi, vaultApi, mcpApi, type McpInfo } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Skeleton } from "@/components/ui/skeleton";

function fmtSize(bytes: number): string {
  if (bytes >= 1e9) return `${(bytes / 1e9).toFixed(1)} GB`;
  return `${Math.round(bytes / 1e6)} MB`;
}

function Section({
  title,
  desc,
  children,
}: {
  title: string;
  desc?: string;
  children: React.ReactNode;
}) {
  return (
    <section className="border-b border-border py-7">
      <h2 className="text-base font-semibold">{title}</h2>
      {desc && <p className="mt-0.5 text-note text-text-muted">{desc}</p>}
      <div className="mt-4">{children}</div>
    </section>
  );
}

export function SettingsView() {
  const theme = useUi((s) => s.theme);
  const setTheme = useUi((s) => s.setTheme);

  return (
    <div className="h-full overflow-y-auto">
      <div className="mx-auto max-w-2xl px-10 py-10">
        <h1 className="text-2xl font-bold tracking-tight">Settings</h1>

        <Section title="Appearance">
          <div className="inline-flex rounded-lg border border-border bg-surface p-0.5">
            {(["light", "dark", "system"] as Theme[]).map((t) => (
              <button
                key={t}
                onClick={() => setTheme(t)}
                className={`rounded-md px-3 py-1 text-sm capitalize transition-colors ${
                  theme === t
                    ? "bg-brand text-brand-fg"
                    : "text-text-muted hover:text-text"
                }`}
              >
                {t}
              </button>
            ))}
          </div>
        </Section>

        <Section
          title="Whisper models"
          desc="Speech-to-text runs entirely on your Mac. Download a model to enable transcription."
        >
          <ModelManager />
        </Section>

        <Section
          title="Ollama (AI summaries)"
          desc="Meeting summaries are generated by a local LLM via Ollama. Optional, transcripts save without it."
        >
          <OllamaStatus />
        </Section>

        <Section
          title="Speaker labels (diarization)"
          desc="Label who-said-what in meeting transcripts. Runs on-device via downloadable models (~35 MB)."
        >
          <DiarizationSettings />
        </Section>

        <Section
          title="Markdown vault"
          desc="Mirror your pages to portable Markdown files you can open and edit in Obsidian, Finder, or git. Edits flow back in."
        >
          <VaultSettings />
        </Section>

        <Section
          title="Agent connection (MCP)"
          desc="Let Claude Code or Codex read and file notes into this workspace via a local MCP server. Read access is always on; enabling writes mints a token."
        >
          <McpSettings />
        </Section>

        <Section title="Privacy & data">
          <div className="flex items-start gap-2.5 rounded-lg bg-brand-soft px-4 py-3 text-sm text-text-muted">
            <Lock className="mt-0.5 size-4 shrink-0" />
            <span>
              All your pages, databases, recordings, and transcripts are stored
              locally on this Mac. Nothing is uploaded and there is no telemetry.
              The only network requests are optional Whisper model downloads and
              your local Ollama.
            </span>
          </div>
        </Section>
      </div>
    </div>
  );
}

function ModelManager() {
  const { data: models, isLoading } = useModels();
  const progress = useDownloadProgress();
  const m = useModelMutations();

  if (isLoading)
    return (
      <div className="space-y-2">
        <Skeleton className="h-12 w-full" />
        <Skeleton className="h-12 w-full" />
      </div>
    );
  if (!models?.length)
    return <div className="text-sm text-text-faint">No models available.</div>;

  return (
    <div className="divide-y divide-border rounded-lg border border-border">
      {models.map((model) => (
        <ModelRow
          key={model.id}
          model={model}
          downloading={m.download.isPending && m.download.variables === model.id}
          progress={progress[model.id]}
          onDownload={() => m.download.mutate(model.id)}
          onSelect={() => m.select.mutate(model.id)}
          onDelete={() => m.remove.mutate(model.id)}
        />
      ))}
    </div>
  );
}

function ModelRow({
  model,
  downloading,
  progress,
  onDownload,
  onSelect,
  onDelete,
}: {
  model: ModelInfo;
  downloading: boolean;
  progress?: number;
  onDownload: () => void;
  onSelect: () => void;
  onDelete: () => void;
}) {
  const pct = progress != null ? Math.round(progress * 100) : null;
  return (
    <div className="flex items-center gap-3 px-4 py-3">
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium">{model.name}</span>
          {model.selected && (
            <span className="inline-flex items-center gap-1 rounded-full bg-brand-soft px-2 py-0.5 text-2xs font-semibold text-brand">
              <Check className="size-3" /> Selected
            </span>
          )}
        </div>
        <div className="text-xs text-text-faint">{fmtSize(model.size)}</div>
        {downloading && pct != null && (
          <div className="mt-1.5 h-1.5 w-40 overflow-hidden rounded-full bg-bg-subtle">
            <div className="h-full bg-brand" style={{ width: `${pct}%` }} />
          </div>
        )}
      </div>
      {!model.downloaded ? (
        <Button size="sm" variant="secondary" onClick={onDownload} disabled={downloading}>
          <Download className="size-3.5" /> {downloading ? `${pct ?? 0}%` : "Download"}
        </Button>
      ) : (
        <div className="flex items-center gap-1.5">
          {!model.selected && (
            <Button size="sm" variant="secondary" onClick={onSelect}>
              Select
            </Button>
          )}
          <button
            aria-label={`Delete ${model.name}`}
            onClick={onDelete}
            className="grid size-8 place-items-center rounded-md text-text-faint hover:bg-surface-hover hover:text-danger-c"
          >
            <Trash2 className="size-4" />
          </button>
        </div>
      )}
    </div>
  );
}

function DiarizationSettings() {
  const enabled = useUi((s) => s.diarizeEnabled);
  const setEnabled = useUi((s) => s.setDiarizeEnabled);
  const { data: available, refetch } = useQuery({
    queryKey: ["diarization-available"],
    queryFn: diarizeApi.available,
  });
  const [downloading, setDownloading] = useState(false);

  const download = async () => {
    setDownloading(true);
    try {
      await diarizeApi.download();
      await refetch();
    } catch (e) {
      console.error(e);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="space-y-3">
      <label className="flex items-center justify-between">
        <span className="text-sm">Label speakers in meeting transcripts</span>
        <Switch checked={enabled} onCheckedChange={setEnabled} />
      </label>
      <div className="flex items-center gap-3">
        <span
          className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-note font-medium ${
            available
              ? "bg-[color-mix(in_srgb,var(--success)_14%,transparent)] text-success"
              : "bg-surface-hover text-text-muted"
          }`}
        >
          <Circle className={`size-2.5 ${available ? "fill-success" : "fill-text-faint"}`} />
          {available ? "Models installed" : "Models not installed"}
        </span>
        {!available && (
          <Button size="sm" variant="secondary" onClick={download} disabled={downloading}>
            <Download className="size-3.5" /> {downloading ? "Downloading…" : "Download models"}
          </Button>
        )}
      </div>
    </div>
  );
}

function OllamaStatus() {
  const { data, isFetching, refetch } = useOllamaStatus();
  const up = data?.available;
  return (
    <div className="flex items-center gap-3">
      <span
        className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-note font-medium ${
          up
            ? "bg-[color-mix(in_srgb,var(--success)_14%,transparent)] text-success"
            : "bg-surface-hover text-text-muted"
        }`}
      >
        <Circle className={`size-2.5 ${up ? "fill-success" : "fill-text-faint"}`} />
        {up ? `Connected · ${data?.models[0] ?? "ready"}` : "Not detected"}
      </span>
      <Button size="sm" variant="secondary" onClick={() => refetch()} disabled={isFetching}>
        <RefreshCw className={`size-3.5 ${isFetching ? "animate-spin" : ""}`} /> Test
      </Button>
      {!up && (
        <a
          href="https://ollama.com"
          target="_blank"
          rel="noreferrer"
          className="text-note text-brand hover:underline"
        >
          Get Ollama →
        </a>
      )}
    </div>
  );
}

function VaultSettings() {
  const qc = useQueryClient();
  const { data: dir } = useQuery({ queryKey: ["vault-dir"], queryFn: () => vaultApi.getDir() });
  const [path, setPath] = useState("");
  const [msg, setMsg] = useState<string | null>(null);

  const setDir = useMutation({
    mutationFn: (p: string) => vaultApi.setDir(p),
    onSuccess: (count) => {
      setMsg(`Vault linked · exported ${count} page${count === 1 ? "" : "s"}`);
      qc.invalidateQueries({ queryKey: ["vault-dir"] });
    },
    onError: (e: unknown) => setMsg(String((e as { message?: string })?.message ?? e)),
  });
  const exportAll = useMutation({
    mutationFn: () => vaultApi.exportAll(),
    onSuccess: (count) => setMsg(`Re-exported ${count} page${count === 1 ? "" : "s"}`),
  });

  return (
    <div className="space-y-3">
      {dir ? (
        <div className="flex items-center gap-3">
          <code className="min-w-0 flex-1 truncate rounded bg-surface px-2.5 py-1.5 text-xs text-text-muted">
            {dir}
          </code>
          <Button size="sm" variant="secondary" onClick={() => exportAll.mutate()} disabled={exportAll.isPending}>
            <RefreshCw className={`size-3.5 ${exportAll.isPending ? "animate-spin" : ""}`} /> Re-export
          </Button>
        </div>
      ) : (
        <p className="text-note text-text-muted">No vault linked yet.</p>
      )}
      <div className="flex items-center gap-2">
        <input
          value={path}
          onChange={(e) => setPath(e.target.value)}
          placeholder="/absolute/path/to/vault-folder"
          className="min-w-0 flex-1 rounded-md border border-border bg-surface px-2.5 py-1.5 text-sm outline-none focus:ring-2 focus:ring-ring"
        />
        <Button
          size="sm"
          onClick={() => path.trim() && setDir.mutate(path.trim())}
          disabled={setDir.isPending || !path.trim()}
        >
          {dir ? "Change" : "Link vault"}
        </Button>
      </div>
      {msg && <p className="text-note text-text-muted">{msg}</p>}
    </div>
  );
}

function McpSettings() {
  const qc = useQueryClient();
  const { data: token } = useQuery({ queryKey: ["mcp-token"], queryFn: () => mcpApi.getToken() });
  const [info, setInfo] = useState<McpInfo | null>(null);
  const [copied, setCopied] = useState(false);

  const enable = useMutation({
    mutationFn: () => mcpApi.enable(),
    onSuccess: (i) => {
      setInfo(i);
      qc.invalidateQueries({ queryKey: ["mcp-token"] });
    },
  });
  const disable = useMutation({
    mutationFn: () => mcpApi.disable(),
    onSuccess: () => {
      setInfo(null);
      qc.invalidateQueries({ queryKey: ["mcp-token"] });
    },
  });

  const enabled = !!token || !!info;
  const cmd = info?.claude_command;

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-3">
        <span
          className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-note font-medium ${
            enabled
              ? "bg-[color-mix(in_srgb,var(--success)_14%,transparent)] text-success"
              : "bg-surface-hover text-text-muted"
          }`}
        >
          <Circle className={`size-2.5 ${enabled ? "fill-success" : "fill-text-faint"}`} />
          {enabled ? "Write access enabled" : "Read-only"}
        </span>
        {enabled ? (
          <Button size="sm" variant="secondary" onClick={() => disable.mutate()} disabled={disable.isPending}>
            Revoke writes
          </Button>
        ) : (
          <Button size="sm" onClick={() => enable.mutate()} disabled={enable.isPending}>
            Enable writes
          </Button>
        )}
      </div>
      {cmd && (
        <div className="space-y-1.5">
          <p className="text-note text-text-muted">
            Register the connector by running this once in your terminal:
          </p>
          <div className="flex items-start gap-2">
            <code className="min-w-0 flex-1 overflow-x-auto whitespace-pre rounded bg-surface px-2.5 py-2 text-xs text-text">
              {cmd}
            </code>
            <Button
              size="sm"
              variant="secondary"
              onClick={() => {
                navigator.clipboard?.writeText(cmd);
                setCopied(true);
                setTimeout(() => setCopied(false), 1500);
              }}
            >
              {copied ? <Check className="size-3.5" /> : "Copy"}
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
